# Setup
title:               7rieden
tagline:             
description:         <b>To be Pro</b>
url:                 https://7rieden.github.io
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Daeyoung Yoon
  url:               https://www.facebook.com/7rieden
  email:             7riedeng@gmail.com

# Gems
plugins:
  - jekyll-paginate

pagination:
    enabled: true
    per_page: 1
    limit: 1
    sort_field: "date"
    sort_reverse: true

# Custom vars
version:             1.1.0
google_analytics_id: UA-168692799-1 #UA-XXXX-Y

highlighter: rouge

category_dir: category/
tag_dir: tag/