# Setup
title:               7rieden
tagline:             
description:         Frieden means Peace in Germeny. <br> This word is my favorite word. <br> And European write down the number 7 like Fender F.<br><br> 7rieden

url:                 https://7rieden.github.io
baseurl:             
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Daeyoung Yoon
  url:               https://www.facebook.com/7rieden
  email:             7riedeng@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Paginate Config
pagination:
    enabled: true
    per_page: 1
    limit: 5
    sort_field: "date"
    sort_reverse: true


#Disqus
disqus:
  shortname: 7rieden-github-io

# Custom vars
version:             1.1.0
google_analytics_id: UA-168692799-1 #UA-XXXX-Y

highlighter: rouge

category_dir: category/
tag_dir: tag/

